from setuptools import setup

setup(
    name='lemonlib',
    version='0.1.0',    
    description='Library used by frc 5113',
    url='https://github.com/FRC5113/LemonLib',
    author='Combustible Lemons',
    author_email='robotics@mtps.us',
    license='Unlicense',
    packages=['lemonlib'],
    install_requires=['bcrypt==4.2.1',
                    'cffi==1.17.1',
                    'colorama==0.4.6',
                    'cryptography==44.0.0',
                    'flexcache==0.3',
                    'flexparser==0.4',
                    'iniconfig==2.0.0',
                    'msvc_runtime==14.42.34433',
                    'numpy==2.2.2',
                    'opencv-python==4.11.0.86',
                    'packaging==23.2',
                    'paramiko==3.5.0',
                    'phoenix6==25.2.1',
                    'photonlibpy==2025.1.1',
                    'Pint==0.24.4',
                    'platformdirs==4.3.6',
                    'pluggy==1.5.0',
                    'pycparser==2.22',
                    'pyfrc==2025.0.0',
                    'PyNaCl==1.5.0',
                    'pynetconsole==2.0.4',
                    'pyntcore==2025.2.1',
                    'pytest==8.3.4',
                    'pytest-reraise==2.1.2',
                    'robotpy==2025.2.1.0',
                    'robotpy-apriltag==2025.2.1',
                    'robotpy-cli==2024.0.0',
                    'robotpy-commands-v2==2025.1.1',
                    'robotpy-cscore==2025.2.1',
                    'robotpy-hal==2025.2.1',
                    'robotpy-halsim-gui==2025.2.1',
                    'robotpy-installer==2025.0.0',
                    'robotpy-wpilib-utilities==2025.0.0',
                    'robotpy-wpimath==2025.2.1',
                    'robotpy-wpinet==2025.2.1',
                    'robotpy-wpiutil==2025.2.1',
                    'setuptools==75.8.0',
                    'tomli==2.2.1',
                    'tomlkit==0.13.2',
                    'typing_extensions==4.12.2',
                    'wpilib==2025.2.1',                    
                      ],

    classifiers=[
        'Development Status :: 3 - Alpha',      
        'Intended Audience :: Developers',      
        'Programming Language :: Python :: 3',
    ],
)