name: Sync LemonLib from 2025-Pelican

on:
  repository_dispatch:
    types: [sync_event]

jobs:
  sync-lemonlib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2

      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: FRC5113/2025-Pelican
          path: source-repo

      - name: Copy changes
        run: |
          rsync -av --delete source-repo/src/lemonlib/ lemonlib/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Sync changes from 2025-Pelican"
          git push
